### ISSUE TITLE
Use bincount and digitize in an example

### ISSUE THREAD

**Issue by stefanv** [HarrietInc/elegant-scipy-submissions#16]
Here's a compact implementation of the Hough line transform.  This used to be in scikit-image, but was replaced later by a Cython implementation:

https://github.com/jaberg/scikits-image/blob/master/skimage/transform/hough_transform.py#L9

**Comment by jni** [comment]
@stefanv awesome! =)

**Comment by jni** [comment]
@stefanv we use bincount in chs 3 and 8, so I'm closing this issue.
