### ISSUE TITLE
to 2d bincount using coo_matrix

### ISSUE THREAD

**Issue by amueller** [HarrietInc/elegant-scipy-submissions#17]
A trick I like is using coo_matrix to do a 2d bincount by using the summing in creating a coo_matrix, such as [here](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/metrics/classification.py#L253).

Not sure if that qualifies, it's more a recipe?

**Comment by stefanv** [comment]
Thanks @amueller!  These are welcome, we can try and work them into side boxes.

**Comment by jni** [comment]
@amueller :+1:! I discovered this a few years ago myself, and it's soooo useful. =) We are writing a chapter on scipy.sparse so this will definitely be included in some form. Thanks!

**Comment by jni** [comment]
@amueller it's in! =) Will let you know when the book is out. =)

**Comment by amueller** [comment]
Sweet :)
