### ISSUE TITLE
Game of Life in 12 lines of python

### ISSUE THREAD

**Issue by rougier** [HarrietInc/elegant-scipy-submissions#19]
Author: Nicolas Rougier (@rougier)
Submitted by: Nicolas Rougier (@rougier)

This is the game of life (cellular automata) in 10 lines of python with numpy.
The code is available from http://www.labri.fr/perso/nrougier/teaching/numpy.100/ (last question).
(code explanations is available from http://www.labri.fr/perso/nrougier/teaching/numpy/numpy.html)

I would also recommend other questions from the same source but I don't know if they fit the elegant scipy submissions.

**Comment by jni** [comment]
@rougier very cool, thank you! We are actually planning to use `scipy.ndimage.generic_filter` to implement it, so this would be a very cool complementary approach to have!

btw we are specifically looking for more examples of `generic_filter` in practice, if you have any. =)

Thank you again!

**Comment by rougier** [comment]
Yes, just made one, I will open a new issue.

**Comment by hdashnow** [comment]
This will be an exercise. Thanks @rougier!
